### PR TITLE
rw performance lock

### LINKED ISSUE #22: Read Performance concurrency issue
https://github.com/eo-cqrs/xfake/blob/ecd9054d28728e9b8653e61b70c4b81580ca3d56/src/main/java/io/github/eocqrs/xfake/InFile.java#L85-L95

better replace to 
```java
...
final ReentrantReadWriteLock rwlock = new ReentrantReadWriteLock();
...
 public XML xml() throws Exception { 
   this.rwlock.readLock().lock()
     try {
       return new XMLDocument( 
         new TextOf( 
           new File( 
             this.name 
           ) 
         ).asString() 
       ); 
     } finally {
       this.rwlock.readLock.unlock();
     }
   }
 } 
```

### PR DESCRIPTION
**Pull request by h1alexbel**
@l3r8yJ take a look please

closes #22

---

## PR-Codex overview
This PR introduces thread safety tests for the `InFile` class and implements a `ReentrantReadWriteLock` to improve concurrency. 

### Detailed summary
- Added `ReentrantReadWriteLock` to `InFile` class for improved concurrency.
- Implemented `readLock()` and `writeLock()` methods to protect XML content.
- Added a `todo` to introduce thread safety tests.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-05-29T10:52:20.829695``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Review by l3r8yJ — CHANGES_REQUESTED** [review]
@h1alexbel we can add concurrent tests, take a look at [this](https://www.yegor256.com/2018/03/27/how-to-test-thread-safety.html)

**Comment by h1alexbel** [comment]
@l3r8yJ interesting
never done this before..

**Comment by h1alexbel** [comment]
@l3r8yJ puzzle created

**Review by l3r8yJ — APPROVED** [review]
@h1alexbel lgtm

**Comment by l3r8yJ** [comment]
@h1alexbel If you don't mind, I can take a new puzzle.

**Comment by h1alexbel** [comment]
@l3r8yJ ok, sure

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
